1. Scenario: A company wants to analyze the sales performance of its products in different regions. They have collected the following data:
   Region A: [10, 15, 12, 8, 14]
   Region B: [18, 20, 16, 22, 25]
   Calculate the mean sales for each region.


In [2]:
A = [10, 15, 12, 8, 14]
B = [18, 20, 16, 22, 25]

In [3]:
import numpy as np
print("Mean of A",np.mean(A))
print("Mean of B",np.mean(B))

Mean of A 11.8
Mean of B 20.2


2. Scenario: A survey is conducted to measure customer satisfaction on a scale of 1 to 5. The data collected is as follows:
   [4, 5, 2, 3, 5, 4, 3, 2, 4, 5]
   Calculate the mode of the survey responses.


In [4]:
import statistics
statistics.mode([4, 5, 2, 3, 5, 4, 3, 2, 4, 5])

4

3. Scenario: A company wants to compare the salaries of two departments. The salary data for Department A and Department B are as follows:
   Department A: [5000, 6000, 5500, 7000]
   Department B: [4500, 5500, 5800, 6000, 5200]
   Calculate the median salary for each department.


In [13]:
A = [5000, 6000, 5500, 7000]
B= [4500, 5500, 5800, 6000, 5200]
print('Median for A:',np.median(A))
print('Median for B:',statistics.median(B))

Median for A: 5750.0
Median for B: 5500


4. Scenario: A data analyst wants to determine the variability in the daily stock prices of a company. The data collected is as follows:
   [25.5, 24.8, 26.1, 25.3, 24.9]
   Calculate the range of the stock prices.


In [45]:
x = [25.5, 24.8, 26.1, 25.3, 24.9]
range_sp = max(x)-min(x)
range_sp

1.3000000000000007

5. Scenario: A study is conducted to compare the performance of two different teaching methods. The test scores of the students in each group are as follows:
   Group A: [85, 90, 92, 88, 91]
   Group B: [82, 88, 90, 86, 87]
   Perform a t-test to determine if there is a significant difference in the mean scores between the two groups.


In [34]:
a = [85, 90, 92, 88, 91]
b = [82, 88, 90, 86, 87]
import scipy.stats as stats
stats.ttest_ind(a, b, equal_var=True)

Ttest_indResult(statistic=1.4312528946642733, pvalue=0.19023970239078333)

since pvalue is greater than 0.05 hence we can say there is no significant difference in the mean scores between two groups

6. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
   Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
   Sales (in thousands): [25, 30, 28, 20, 26]
   Calculate the correlation coefficient between advertising expenditure and sales.


In [7]:
print(np.corrcoef([10, 15, 12, 8, 14], [25, 30, 28, 20, 26]))


[[1.         0.87575114]
 [0.87575114 1.        ]]


7. Scenario: A survey is conducted to measure the heights of a group of people. The data collected is as follows:
   [160, 170, 165, 155, 175, 180, 170]
   Calculate the standard deviation of the heights.


In [6]:
np.std([160, 170, 165, 155, 175, 180, 170])

7.953949089757174

8. Scenario: A company wants to analyze the relationship between employee tenure and job satisfaction. The data collected is as follows:
   Employee Tenure (in years): [2, 3, 5, 4, 6, 2, 4]
   Job Satisfaction (on a scale of 1 to 10): [7, 8, 6, 9, 5, 7, 6]
   Perform a linear regression analysis to predict job satisfaction based on employee tenure.


In [32]:
from sklearn.linear_model import LinearRegression
import pandas as pd
r = LinearRegression()
x =  [2, 3, 5, 4, 6, 2, 4] 
y =  [7, 8, 6, 9, 5, 7, 6]
x = pd.DataFrame(x)

r.fit(x,y)
r.predict([[1]])

array([8.12765957])

9. Scenario: A study is conducted to compare the effectiveness of two different medications. The recovery times of the patients in each group are as follows:
   Medication A: [10, 12, 14, 11, 13]
   Medication B: [15, 17, 16, 14, 18]
   Perform an analysis of variance (ANOVA) to determine if there is a significant difference in the mean recovery times between the two medications.


In [33]:
from scipy.stats import f_oneway

a = [10, 12, 14, 11, 13]
b = [15, 17, 16, 14, 18]

f_oneway(a,b)


F_onewayResult(statistic=16.0, pvalue=0.003949772803445326)

Since pvalue is less than .05 hence there is a significant difference between two medications


10. Scenario: A company wants to analyze customer feedback ratings on a scale of 1 to 10. The data collected is

 as follows:
    [8, 9, 7, 6, 8, 10, 9, 8, 7, 8]
    Calculate the 75th percentile of the feedback ratings.


In [30]:
import numpy as np
x =  [8, 9, 7, 6, 8, 10, 9, 8, 7, 8]
q3 = np.quantile(x,.75)
q3

8.75

11. Scenario: A quality control department wants to test the weight consistency of a product. The weights of a sample of products are as follows:
    [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]
    Perform a hypothesis test to determine if the mean weight differs significantly from 10 grams.


In [38]:
import scipy.stats as stats
data =  [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]
t_statistic, p_value = stats.ttest_1samp(a=data, popmean=10)
print(t_statistic , p_value)


1.5126584522688367 0.19077595151110102


since pvalue is greater than 0.05 hence the mean weight do not differs significantly from 10 grams.

12. Scenario: A company wants to analyze the click-through rates of two different website designs. The number of clicks for each design is as follows:
    Design A: [100, 120, 110, 90, 95]
    Design B: [80, 85, 90, 95, 100]
    Perform a chi-square test to determine if there is a significant difference in the click-through rates between the two designs.


In [41]:
from scipy.stats import chi2_contingency
A = [100, 120, 110, 90, 95]
B = [80, 85, 90, 95, 100]
stat, p, dof, expected = chi2_contingency(A,B)
p

1.0

since pvalue is greater than 0.05 hence there is no significant difference in the click-through rates between the two designs.

13. Scenario: A survey is conducted to measure customer satisfaction with a product on a scale of 1 to 10. The data collected is as follows:
    [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]
    Calculate the 95% confidence interval for the population mean satisfaction score.


In [44]:
import numpy as np
import scipy.stats as st
data = [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]
st.t.interval(0.95, df=len(data)-1,
			loc=np.mean(data),
			scale=st.sem(data))


(7.043561120599888, 8.756438879400113)

14. Scenario: A company wants to analyze the effect of temperature on product performance. The data collected is as follows:
    Temperature (in degrees Celsius): [20, 22, 23, 19, 21]
    Performance (on a scale of 1 to 10): [8, 7, 9, 6, 8]
    Perform a simple linear regression to predict performance based on temperatur


In [26]:
from sklearn.linear_model import LinearRegression
import pandas as pd
r = LinearRegression()
x =  [20, 22, 23, 19, 21]
y = [8, 7, 9, 6, 8]
x = pd.DataFrame(x)

r.fit(x,y)
r.predict([[21]])

array([7.6])


15. Scenario: A study is conducted to compare the preferences of two groups of participants. The preferences are measured on a Likert scale from 1 to 5. The data collected is as follows:
    Group A: [4, 3, 5, 2, 4]
    Group B: [3, 2, 4, 3, 3]
    Perform a Mann-Whitney U test to determine if there is a significant difference in the median preferences between the two groups.


In [37]:
from scipy.stats import mannwhitneyu
batch_1 =  [4, 3, 5, 2, 4]
batch_2 = [3, 2, 4, 3, 3]
stat, p_value = mannwhitneyu(batch_1, batch_2)
print('Statistics=%.2f, p=%.2f' % (stat, p_value))
alpha = 0.05
if p_value < alpha:
	print('Reject Null Hypothesis (Significant difference between two samples)')
else:
	print('Do not Reject Null Hypothesis (No significant difference between two samples)')


Statistics=17.00, p=0.38
Do not Reject Null Hypothesis (No significant difference between two samples)


16. Scenario: A company wants to analyze the distribution of customer ages. The data collected is as follows:
    [25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
    Calculate the interquartile range (IQR) of the ages.


In [12]:
x = [25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
q1 = np.quantile(x,.25)
q3 = np.quantile(x,.75)
iqr = q3-q1
print(iqr)

22.5


17. Scenario: A study is conducted to compare the performance of three different machine learning algorithms. The accuracy scores for each algorithm are as follows:
    Algorithm A: [0.85, 0.80, 0.82, 0.87, 0.83]
    Algorithm B: [0.78, 0.82, 0.84, 0.80, 0.79]
    Algorithm C: [0.90, 0.88, 0.89, 0.86, 0.87]
    Perform a Kruskal-Wallis test to determine if there is a significant difference in the median accuracy scores between the algorithms.


In [36]:
from scipy import stats
A = [0.85, 0.80, 0.82, 0.87, 0.83]
B = [0.78, 0.82, 0.84, 0.80, 0.79]
C = [0.90, 0.88, 0.89, 0.86, 0.87]
result = stats.kruskal(A,B,C)
print(result)


KruskalResult(statistic=9.696947935368053, pvalue=0.007840333026249539)


since pvalue is less than 0.05 there is a significant difference in the median accuracy scores between the algorithms.

18. Scenario: A company wants to analyze the effect of price on sales. The data collected is as follows:
    Price (in dollars): [10, 15, 12, 8, 14]
    Sales: [100, 80, 90, 110, 95]
    Perform a simple linear regression to predict

 sales based on price.


In [24]:
from sklearn.linear_model import LinearRegression
import pandas as pd
r = LinearRegression()
x = [10, 15, 12, 8, 14]
y = [100, 80, 90, 110, 95]
x = pd.DataFrame(x)

r.fit(x,y)
r.predict([[11]])

array([97.80487805])

19. Scenario: A survey is conducted to measure the satisfaction levels of customers with a new product. The data collected is as follows:
    [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]
    Calculate the standard error of the mean satisfaction score.


In [35]:
import math

data = [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]
sample_size = len(data)
mean = sum(data) / sample_size
squared_deviations = [(x - mean) ** 2 for x in data]
variance = sum(squared_deviations) / (sample_size - 1)
standard_deviation = math.sqrt(variance)
standard_error = standard_deviation / math.sqrt(sample_size)

print("Standard Error:", standard_error)


Standard Error: 0.3055050463303893


20. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
    Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
    Sales (in thousands): [25, 30, 28, 20, 26]
    Perform a multiple regression analysis to predict sales based on advertising expenditure.


In [31]:
from sklearn.linear_model import LinearRegression
import pandas as pd
r = LinearRegression()
x =  [10, 15, 12, 8, 14] 
y = [25, 30, 28, 20, 26]
x = pd.DataFrame(x)

r.fit(x,y)
r.predict([[11]])

array([24.87804878])